INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "iPhone 30XXL rip off", "Technology", 500000, "20200530", ":20200601");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "New Awesome Game", "Technology", 23000, "20190215", "20450101");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "Catsitting", "Animals", 1000, "20181031", "20181111");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "New Year New Me Program", "Exercise", 2500, "20200101", "20203112");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "I need some new pants", "Party Services", 100, "20190401", "20190402");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "Jerry's Magic Show", "Party Services", 5500, "20170525", "20170712");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "Building Homeless Shelters", "Housing", 70000000, "20250824", "20281122");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "Bring Arts Back to Grade Schools", "Education", 9000000, "20210718", "20230913");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "Research in Archaeological Sites", "Archaeology", 4400000, "20080930", "20090720");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "The Final Project", "Finale", 10, "20301231","20501231");

INSERT INTO users (id, name, age) VALUES (1, "Ace", 21);
INSERT INTO users (id, name, age) VALUES (2, "Barry", 25);
INSERT INTO users (id, name, age) VALUES (3, "Alice", 18);
INSERT INTO users (id, name, age) VALUES (4, "Teria", 19);
INSERT INTO users (id, name, age) VALUES (5, "Vin", 20);
INSERT INTO users (id, name, age) VALUES (6, "Winston", 29);
INSERT INTO users (id, name, age) VALUES (7, "McCree", 21);
INSERT INTO users (id, name, age) VALUES (8, "Ken", 18);
INSERT INTO users (id, name, age) VALUES (9, "Que", 18);
INSERT INTO users (id, name, age) VALUES (10, "Claire", 25);
INSERT INTO users (id, name, age) VALUES (11, "Santa", 24);
INSERT INTO users (id, name, age) VALUES (12, "Faye", 27);
INSERT INTO users (id, name, age) VALUES (13, "Gary", 32);
INSERT INTO users (id, name, age) VALUES (14, "Erin", 45);
INSERT INTO users (id, name, age) VALUES (15, "Din", 42);
INSERT INTO users (id, name, age) VALUES (16, "Naryu", 32);
INSERT INTO users (id, name, age) VALUES (17, "Hoenn", 58);
INSERT INTO users (id, name, age) VALUES (18, "Zanar", 22);
INSERT INTO users (id, name, age) VALUES (19, "Xion", 19);
INSERT INTO users (id, name, age) VALUES (20, "Marr", 76);

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 10, 1, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 15, 2, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 100, 5, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 40, 6, 5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 157, 5, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 100, 3, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 160, 19, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 1880, 20, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 120, 15, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 12400, 15, 5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 1050, 14, 4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 80, 14, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 1, 12, 7);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 4, 12, 2);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 34, 12, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 56, 5, 4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 74, 3, 4);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 44, 8, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 21, 9, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 6, 17, 1);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 78, 14, 5);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 1090, 13, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 89, 11, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 96, 10, 8);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 324, 9, 3);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 16, 5, 10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 17, 2, 10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 14, 8, 10);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 36, 1, 6);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 111, 2, 3);
